Lekkerbek.web/Controllers/InstellingenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.web.Entities;
using Lekkerbek.web.Models;

namespace Lekkerbek.web.Controllers
{
    public class InstellingenController : Controller
    {
        private readonly LekkerbekDbContext _context;

        public InstellingenController(LekkerbekDbContext context)
        {
            _context = context;
        }

        // GET: Instellingen
        public async Task<IActionResult> Index()
        {
              return View(await _context.Instellingen.ToListAsync());
        }

        // GET: Instellingen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Instellingen == null)
            {
                return NotFound();
            }

            var tblInstellingen = await _context.Instellingen
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblInstellingen == null)
            {
                return NotFound();
            }

            return View(tblInstellingen);
        }

        // GET: Instellingen/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Instellingen/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naam,Straat,Huisnr,Postcode,Stad,Email,Telefoon,TijdslotInterval")] TblInstellingen tblInstellingen)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblInstellingen);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblInstellingen);
        }

        // GET: Instellingen/Edit/5
        public async Task<IActionResult> Edit()
        {
            //A>Get data uit database
            //--------------------------
            int id = _context.Instellingen.FirstOrDefault().Id;
            var tblInstellingen = await _context.Instellingen.FindAsync(id);

            if (tblInstellingen == null)
            {
                return NotFound();
            }

            //B>Vul model
            //--------------
            InstellingenModel model = new()
            {
                Id = id,        
                Naam = tblInstellingen.Naam,
                Straat = tblInstellingen.Straat,
                Huisnr = tblInstellingen.Huisnr,
                Postcode = tblInstellingen.Postcode,
                Stad = tblInstellingen.Stad,

                Email = tblInstellingen.Email,
                Telefoon = tblInstellingen.Telefoon,

                TijdslotInterval = tblInstellingen.TijdslotInterval,

                GetrouwheidScoreLimiet = tblInstellingen.GetrouwheidScoreLimiet,

                KortingWaardeInDecimaal = (tblInstellingen.KortingWaardeInDecimaal).ToString(),

                BtwInDecimaal = ( tblInstellingen.BtwInDecimaal).ToString(),

                AfzenderAdres = tblInstellingen.AfzenderAdres,
                AfzenderNaam = tblInstellingen.AfzenderNaam,
                Onderwerp = tblInstellingen.Onderwerp,
                SmtpPort  = tblInstellingen.SmtpPort,
                SmtpHost = tblInstellingen.SmtpHost,
                Login = tblInstellingen.Login,
                Paswoord =  tblInstellingen.Paswoord

            };


            //> Layout data
            ViewBag.Layout = _context.LoginData.FirstOrDefault().Layout;

            return View(model);
        }

        // POST: Instellingen/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, InstellingenModel model)
        {
            
            //A> Data input
            //-------------
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //B> Vullen van het tblModel
                    //---------------------------

                    TblInstellingen tblInstellingen = new TblInstellingen()
                    {
                        Id = (int)id,
                        Naam = model.Naam,
                        Straat = model.Straat,
                        Huisnr = model.Huisnr,
                        Postcode = model.Postcode,
                        Stad = model.Stad,

                        Email = model.Email,
                        Telefoon = model.Telefoon,

                        TijdslotInterval = model.TijdslotInterval,

                        GetrouwheidScoreLimiet = model.GetrouwheidScoreLimiet,

                            
                        KortingWaardeInDecimaal = (float)Math.Round(float.Parse(model.KortingWaardeInDecimaal),2),//dit is een string dat naar float moet worden omgezet

                        BtwInDecimaal = (float)Math.Round(float.Parse(model.BtwInDecimaal),2)//dit is een string dat naar float moet worden omgezet
                    };


                    _context.Update(tblInstellingen);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblInstellingenExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(insertOkMsg));
            }
            return View(model);
        }

        public IActionResult insertOkMsg()
        {
            //Layout en rol data
            ViewBag.Layout = _context.LoginData.FirstOrDefault().Layout;
            ViewBag.Rol = _context.LoginData.FirstOrDefault().Rol;

            return View();
        }

        // GET: Instellingen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Instellingen == null)
            {
                return NotFound();
            }

            var tblInstellingen = await _context.Instellingen
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblInstellingen == null)
            {
                return NotFound();
            }

            return View(tblInstellingen);
        }

        // POST: Instellingen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Instellingen == null)
            {
                return Problem("Entity set 'LekkerbekDbContext.Instellingen'  is null.");
            }
            var tblInstellingen = await _context.Instellingen.FindAsync(id);
            if (tblInstellingen != null)
            {
                _context.Instellingen.Remove(tblInstellingen);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblInstellingenExists(int id)
        {
          return _context.Instellingen.Any(e => e.Id == id);
        }
    }
}

Lekkerbek.web/Views/Instellingen/Create.cshtml
@model Lekkerbek.web.Entities.TblInstellingen

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TblInstellingen</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Straat" class="control-label"></label>
                <input asp-for="Straat" class="form-control" />
                <span asp-validation-for="Straat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Huisnr" class="control-label"></label>
                <input asp-for="Huisnr" class="form-control" />
                <span asp-validation-for="Huisnr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postcode" class="control-label"></label>
                <input asp-for="Postcode" class="form-control" />
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stad" class="control-label"></label>
                <input asp-for="Stad" class="form-control" />
                <span asp-validation-for="Stad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefoon" class="control-label"></label>
                <input asp-for="Telefoon" class="form-control" />
                <span asp-validation-for="Telefoon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TijdslotInterval" class="control-label"></label>
                <input asp-for="TijdslotInterval" class="form-control" />
                <span asp-validation-for="TijdslotInterval" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.web/Views/Instellingen/Delete.cshtml
@model Lekkerbek.web.Entities.TblInstellingen

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblInstellingen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Straat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Straat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Huisnr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Huisnr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefoon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefoon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TijdslotInterval)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TijdslotInterval)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Lekkerbek.web/Views/Instellingen/Details.cshtml
@model Lekkerbek.web.Entities.TblInstellingen

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TblInstellingen</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Straat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Straat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Huisnr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Huisnr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefoon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefoon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TijdslotInterval)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TijdslotInterval)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Lekkerbek.web/Views/Instellingen/Edit.cshtml
@model Lekkerbek.web.Models.InstellingenModel

@{
    ViewData["Title"] = "Edit";
    Layout = ViewBag.Layout;
}

<form asp-action="Edit">
    <div class="card-deck"> 

        <div class="card text-center shadow-sm" style="max-width:25rem;">
        <div class="card-header bg-danger text-white"><h5>Instellingen:</h5>  </div>
        @*<img src="/img/klanten.png" class="card-img-top">*@
        <div id ="card-body-form text-left" class="card-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />

                    <table class="table">
                        <tr><td class="text-left" colspan="2"><Strong><span class="text-primary">Adres van het bedrijf</span></Strong></td></tr>
                        <tr>
                            <td class="text-left" colspan="2">
                                <div class="form-group">
                                <label asp-for="Naam" class="control-label"></label>
                                <input asp-for="Naam" class="form-control" />
                                <span asp-validation-for="Naam" class="text-danger"></span>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                <div class="form-group">
                                <label asp-for="Straat" class="control-label"></label>
                                <input asp-for="Straat" class="form-control col-14" />
                                <span asp-validation-for="Straat" class="text-danger"></span>
                                </div>
                            </td>
                            <td class="text-left">
                                <div class="form-group">
                                <label asp-for="Huisnr" class="control-label"></label>
                                <input asp-for="Huisnr" class="form-control col-6"  />
                                <span asp-validation-for="Huisnr" class="text-danger"></span>
                                </div>
                            </td>
                        </tr>
                        
                        <tr>                         
                            <td class="text-left">
                                <div class="form-group">
                                <label asp-for="Stad" class="control-label"></label>
                                <input asp-for="Stad" class="form-control col-14"/>
                                <span asp-validation-for="Stad" class="text-danger"></span>
                                </div>
                            </td>
                            <td class="text-left">
                                <div class="form-group">
                                <label asp-for="Postcode" class="control-label"></label>
                                <input asp-for="Postcode" class="form-control col-6" />
                                <span asp-validation-for="Postcode" class="text-danger"></span>
                                </div>
                            </td>
                        </tr>

                        <tr>
                            <td class="text-left" colspan="2">
                                <div class="form-group">
                                <label asp-for="Email" class="control-label"></label>
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left" colspan="2">
                                <div class="form-group">
                                <label asp-for="Telefoon" class="control-label"></label>
                                <input asp-for="Telefoon" class="form-control" />
                                <span asp-validation-for="Telefoon" class="text-danger"></span>
                                </div>
                            </td>
                        </tr>
 
                    </table>
                
                
                    <h5><span class="text-primary">Instellingen voor tijdsloten</span></h5>
                    <div class="form-group">
                        <label asp-for="TijdslotInterval" class="control-label"></label>
                        <input asp-for="TijdslotInterval" class="form-control" />
                        <span asp-validation-for="TijdslotInterval" class="text-danger"></span>
                    </div>
               

               
                    <h5><span class="text-primary">Facturatie instellingen</span></h5>
                    <div class="form-group">
                        <label asp-for="GetrouwheidScoreLimiet" class="control-label"></label>
                        <input asp-for="GetrouwheidScoreLimiet" class="form-control" />
                        <span asp-validation-for="GetrouwheidScoreLimiet" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="KortingWaardeInDecimaal" class="control-label"></label>
                        <input asp-for="KortingWaardeInDecimaal"   class="form-control" />
                        <span asp-validation-for="KortingWaardeInDecimaal" class="text-danger"></span>
                    </div>
                
                    <div class="form-group">
                        <label asp-for="BtwInDecimaal" class="control-label"></label>
                        <input asp-for="BtwInDecimaal"   class="form-control" />
                        <span asp-validation-for="BtwInDecimaal" class="text-danger"></span>
                    </div>
                

        </div>
        <div class="card-footer bg-danger">
                     <input type="submit" value="Save" class="btn btn-warning" />    
        </div>
    </div>
    <!---------------->
    <div  class="card text-center" width="25rem">
        <div class="card-header bg-danger"><h5>Email instellingen:</h5>  </div>
        <div class="card-body">
           <table class="table">
               <tr>
                            <td class="text-left" colspan="2">
                                <div class="form-group">
                                <label asp-for="AfzenderAdres" class="control-label"></label>
                                <input asp-for="AfzenderAdres" class="form-control" />
                                <span asp-validation-for="AfzenderAdres" class="text-danger"></span>
                                </div>
                            </td>
               </tr>
               <tr>
                            <td class="text-left" colspan="2">
                                <div class="form-group">
                                <label asp-for="AfzenderNaam" class="control-label"></label>
                                <input asp-for="AfzenderNaam" class="form-control" />
                                <span asp-validation-for="AfzenderNaam" class="text-danger"></span>
                                </div>
                            </td>
               </tr>
               <tr>
                            <td class="text-left" colspan="2">
                                <div class="form-group">
                                <label asp-for="Onderwerp" class="control-label"></label>
                                <input asp-for="Onderwerp" class="form-control" />
                                <span asp-validation-for="Onderwerp" class="text-danger"></span>
                                </div>
                            </td>
               </tr>
               <tr>
                            <td class="text-left">
                                <div class="form-group">
                                <label asp-for="SmtpHost" class="control-label"></label>
                                <input asp-for="SmtpHost" class="form-control" />
                                <span asp-validation-for="SmtpHost" class="text-danger"></span>
                                </div>
                            </td>
                            <td class="text-left">
                                <div class="form-group">
                                <label asp-for="SmtpPort" class="control-label"></label>
                                <input asp-for="SmtpPort" class="form-control" />
                                <span asp-validation-for="SmtpPort" class="text-danger"></span>
                                </div>
                            </td>
               </tr>
               <tr>
                            <td class="text-left" colspan="2">
                                <div class="form-group">
                                <label asp-for="Login" class="control-label"></label>
                                <input asp-for="Login" class="form-control" />
                                <span asp-validation-for="Login" class="text-danger"></span>
                                </div>
                            </td>
               </tr>
               <tr>
                            <td class="text-left" colspan="2">
                                <div class="form-group">
                                <label asp-for="Paswoord" class="control-label"></label>
                                <input asp-for="Paswoord" class="form-control" />
                                <span asp-validation-for="Paswoord" class="text-danger"></span>
                                </div>
                            </td>
               </tr>
           </table>
        </div>
        <div class="card-footer bg-danger ">
            <input type="submit" value="Save" class="btn btn-warning" />  
        </div>
    </div>
</div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lekkerbek.web/Views/Instellingen/Index.cshtml
@model IEnumerable<Lekkerbek.web.Entities.TblInstellingen>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Straat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Huisnr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Postcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefoon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TijdslotInterval)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Straat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Huisnr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Postcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefoon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TijdslotInterval)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>   
            </td>
        </tr>
}
    </tbody>
</table>

Lekkerbek.web/Views/Instellingen/insertOkMsg.cshtml
@{
     ViewData["Title"] = "insertOkMsg";
     Layout=ViewBag.Layout;

}


<div class="card-deck">

    <div class="card text-center" style="max-width:25rem;">
        <div class="card-header bg-danger"><h5>Alert!!</h5>  </div>
        <img src="/img/ordering.png" class="card-img-top">
        <div class="card-body">
            <h3>Instellingen geupdated </h3><br />           
        </div>
        <div class="card-footer bg-danger">    
            <a  asp-controller="Instellingen" asp-action="Index" >Back to Homepage</a>
        </div>
    </div>
</div>