Lekkerbek.web/Controllers/BestellingenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lekkerbek.web.Entities;
using Lekkerbek.web.Models;
using System.Net.Mail;


namespace Lekkerbek.web.Controllers
{
    public class BestellingenController : Controller
    {
        private readonly LekkerbekDbContext _context;

        public BestellingenController(LekkerbekDbContext context)
        {
            _context = context;
        }

        // GET: Bestellingen
        public  IActionResult Index()
        {
            //A> Data uit database
            //-----------------------
            var bestellingsData = _context.Bestellingen.Include(t => t.Klant);

            //B> Vul lijst met bestellingsmodels
            //-------------------------------------
            List <BestellingOverzichtModel> overzicht = new();
            foreach(var item in bestellingsData)
            {
                BestellingOverzichtModel model = new();
               

                var naam = (from s in _context.Bestellingen
                                 join c in _context.Klanten
                                  on s.KlantId equals c.Id
                                 where s.Id == item.Id
                                 select new { VolledigeNaam = c.Voornaam + ' ' + c.Naam }).FirstOrDefault();
                if (naam != null) { model.KlantNaam = naam.VolledigeNaam; }
                    
                model.AfhaalTijdstip = item.AfhaalTijdstip;
                model.AantalMaaltijden = item.AantalMaaltijden;
                    var PrijsGerechten = from s in _context.Bestellingen
                                         join c in _context.BesteldeGerechten
                                         on s.Id equals c.BestellingId
                                         join d in _context.Gerechten
                                         on c.GerechtenId equals d.Id
                                         where s.Id == item.Id
                                         select d.Prijs;
                    float totalePrijs = 0;
                    foreach(var i in PrijsGerechten) { totalePrijs += i; }
                    var PrijsOpties =    from s in _context.Bestellingen
                                         join c in _context.BesteldeGerechten
                                         on s.Id equals c.BestellingId
                                         join d in _context.GerechtOpties
                                         on c.GerechtOptiesId equals d.Id
                                         where s.Id == item.Id
                                         select d.Prijs;
                    float totaleOptiesPrijs = 0;


                    foreach (var j in PrijsOpties) { totaleOptiesPrijs += j; }


                //prijs berekening
                //----------------------
                     float btw = _context.Instellingen.FirstOrDefault().BtwInDecimaal;
                     model.TotalePrijs =(float) ((totalePrijs + totaleOptiesPrijs) * btw);

                model.Id = item.Id;

                //B1>check of bestelling bestaat in facturatie tabel zoniet moet de knop afrekenen verschijnen in index
                //------------------------------------------------------------------------------------------------------
                var facturatieAfgehandeld =(bool) (from s in _context.Facturaties
                                            join t in _context.Afgehandeld
                                            on s.Id equals t.FacturatieId
                                            where s.Id == item.Id
                                            select t.Afgehandeld).FirstOrDefault();

                if (facturatieAfgehandeld == true)
                {
                    model.Betaald = (bool)(from s in _context.Facturaties
                                           join t in _context.Afgehandeld
                                           on s.Id equals t.FacturatieId
                                           where s.Id == item.Id
                                           select t.Afgehandeld).FirstOrDefault(); 
                }
                
                else 
                {
                    model.Betaald = false;
                }
                overzicht.Add(model);
            }

            //C> Set layout en andere viewbags
            //--------------
            ViewBag.LoginData = _context.LoginData.FirstOrDefault();
            

            return View(overzicht);
        }

       // GET: Bestellingen/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //a> Opvragen van de nodige data uit de database
            //----------------------------------------------
            var bestelling = _context.Bestellingen.Find(id);

            var gerechten = (from s in _context.BesteldeGerechten
                             join c in _context.Gerechten
                              on s.GerechtenId equals c.Id
                             where s.BestellingId == id
                             select new { c.GerechtNaam, c.Prijs }).ToList();

            var gerechtOpties = (from s in _context.BesteldeGerechten
                                 join c in _context.GerechtOpties
                                  on s.GerechtOptiesId equals c.Id
                                 where s.BestellingId == id
                                 select new { c.Optie, c.Prijs }).ToList();

            var klantInfo = (from s in _context.Bestellingen
                             join c in _context.Klanten
                              on s.KlantId equals c.Id
                             where s.Id == id
                             select new { VolledigeNaam = c.Voornaam + ' ' + c.Naam, c.Adres, c.KlantDetailsId, c.Getrouwheidscore }).FirstOrDefault();

            var klantInfoDetails = _context.KlantDetails.Where(s => s.Id == klantInfo.KlantDetailsId).FirstOrDefault();


            //B> Maak een lijst met gerechten
            //---------------------------------
            List<GerechtenModel> gerechtenLijst = new();

            for (int i = 0; i < gerechten.Count; i++)
            {
                GerechtenModel model = new()
                {
                    GerechtNaam = gerechten[i].GerechtNaam,
                    GerechtPrijs = gerechten[i].Prijs,
                    Optie = gerechtOpties[i].Optie,
                    OptiePrijs = gerechtOpties[i].Prijs

                };

                gerechtenLijst.Add(model);
            }


            //C> Vul het factuurModel in
            //----------------------------

            FactuurModel details = new()
            {
                //bestelling
                Id = (int)id,
                GerechtenLijst = gerechtenLijst,
                AantalMaaltijden = gerechten.Count,
                AfhaalTijdstip = bestelling.AfhaalTijdstip,

                //klant
                KlantNaam = klantInfo.VolledigeNaam,
                Adres = klantInfo.Adres,
                Straat = klantInfoDetails.Straat,
                HuisNr = klantInfoDetails.Huisnr,
                Postcode = klantInfoDetails.Postcode,
                Stad = klantInfoDetails.Stad,
                Email = klantInfoDetails.Email,
                Telefoon = klantInfoDetails.Telefoon,

                //layout
                Layout = _context.LoginData.FirstOrDefault().Layout

            };

            //C> Berekening van het verschuldigd bedrag
            //-------------------------------------------------------------------------------
            float totaalPrijsZonderBtw = 0;
            float totaalPrijsMetBtw = 0;
            float btw = _context.Instellingen.FirstOrDefault().BtwInDecimaal;

            for (int i = 0; i < gerechten.Count; i++)
            {
                totaalPrijsZonderBtw += gerechten[i].Prijs;
                totaalPrijsZonderBtw += gerechtOpties[i].Prijs;
            }

            totaalPrijsMetBtw = (float)(totaalPrijsZonderBtw  * btw);
            ViewData["TotaalPrijs"] = totaalPrijsMetBtw;

            //D>Set layout
            //--------------
            ViewBag.Layout = _context.LoginData.FirstOrDefault().Layout;
            ViewBag.Rol = _context.LoginData.FirstOrDefault().Rol;
           
            return View(details);

        }

       
        public IActionResult Factuur(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //a> Opvragen van de nodige data uit de database
            //----------------------------------------------
            var bestelling =  _context.Bestellingen.Find(id);

            var gerechten = (from s in _context.BesteldeGerechten
                             join c in _context.Gerechten
                              on s.GerechtenId equals c.Id
                             where s.BestellingId == id
                             select new { c.GerechtNaam, c.Prijs }).ToList();

            var gerechtOpties = (from s in _context.BesteldeGerechten
                                 join c in _context.GerechtOpties
                                  on s.GerechtOptiesId equals c.Id
                                 where s.BestellingId == id
                                 select new { c.Optie, c.Prijs }).ToList();
 
            var klantInfo = (from s in _context.Bestellingen
                             join c in _context.Klanten
                              on s.KlantId equals c.Id
                             where s.Id == id
                             select new { VolledigeNaam = c.Voornaam + ' ' + c.Naam, c.Adres, c.KlantDetailsId, c.Getrouwheidscore}).FirstOrDefault();

Lekkerbek.web/Views/Bestellingen/Create.cshtml
@model Lekkerbek.web.Models.BestellingModel

@{
    ViewData["Title"] = "Create";
    Layout = Model.Layout;
}

<h3> Nieuwe Bestelling</h3>


<div class="card-deck">
<form asp-action="Create">
    <div class="card text-center" style="max-width:25rem;">
        <div class="card-header bg-warning"><h5>Bestelling:</h5>  </div>
        <img src="/img/ordering.png" class="card-img-top">
        <div class="card-body">
           
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="KlantId" class="control-label">Kies klant:</label>
                    <select asp-for="KlantId" class="form-control" asp-items="ViewBag.KlantId"></select>
                </div>

                <div class="form-group">
                    <input type="hidden" asp-for="Id" id="Id" name="Id" value="@Model.Id">
                    <input type="submit" name="addGerecht" id="addGerecht" formaction='@Url.Action("addGerecht","Bestellingen")' value="Voeg gerecht toe" />
                </div>

                @*<div class="form-group">
                    <label>Selecteer datum voor een Tijdslot</label>
                    <select id="geselecteerdeDag" name="geselecteerdeDag" class='form-control' asp-items='@ViewBag.DatumSelectie'></select>
                    <br />*@
                 <input type="hidden" asp-for="AfhaalTijdstip" id="AfhaalTijdstip" name="AfhaalTijdstip" value="@Model.AfhaalTijdstip">
                    @*<input type="submit" name="kiesTijdSlot" id="kiesTijdSlot" formaction='@Url.Action("kiesTijdSlot","Bestellingen")' value="Kies tijdslot" />
                </div>*@
      
        </div>
   
        <div class="card-footer bg-warning">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
 </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Lekkerbek.web/Views/Bestellingen/Edit.cshtml
@model Lekkerbek.web.Models.FactuurModel

@{
    ViewData["Title"] = "Edit";
    var klantInfo =  ViewBag.KlantInfo;
     Layout = Model.Layout;
}

<h3>Bestelling</h3>


 <div class="card-deck">
     <div class="row hidden-md-up">
<!--Form-->
    <div class="card text-center" style="max-width:25rem;">
        
        <form asp-action="Edit">
            <div class="card-header bg-warning"><h5>BestellingFormulier:</h5>  </div>
            <img src="/img/ordering.png" class="card-img-top">
           <!--hide/unhide form A-->
            <div id ="card-body-form" class="card-body">
            
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
               
                    <div class="form-group">
                        <label asp-for="KlantId" class="control-label">Selecteer Klant</label>
                        <select asp-for="KlantId" class="form-control" asp-items="ViewBag.KlantId"></select>
                        <span asp-validation-for="KlantId" class="text-danger"></span>
                    </div>

                
                    <div class="form-group">  
                        <input type="hidden" asp-for="Id" id="Id" name="Id" value="@Model.Id">
                        <input class="btn btn-outline-info btn-block" type="submit" name="addGerecht" id="addGerecht" formaction='@Url.Action("addGerecht","Bestellingen")' value="Voeg gerecht toe" />
                    </div>
                    <div class="form-group">
                        <input type="hidden" asp-for="Id" id="Id" name="Id" value="@Model.Id">
                        <input class="btn btn-outline-warning btn-block" type="submit" name="lijstBesteldeGerechten" id="lijstBesteldeGerechten" formaction='@Url.Action("Index","BesteldeGerechten")' value="Lijst bestelde gerechten" />
                    </div>
                
                    <div class="form-group">
                        <label>Verander het geselecteerde tijdslot <br /> 
                               (tot max. 1 uur voor bestelling!)</label>
                        <select id="geselecteerdeDag" name="geselecteerdeDag" class='form-control' asp-items='@ViewBag.DatumSelectie'></select>
                        <br />
                        <input class="btn btn-outline-info btn-block" type="submit" name="kiesTijdSlot" id="kiesTijdSlot" formaction='@Url.Action("kiesTijdSlot","Bestellingen")' value="Kies een tijdslot" />
                    </div>

                    <div class="form-group">
                        <p>
                            <input type="hidden" asp-for="AfhaalTijdstip" value="@Model.AfhaalTijdstip" />
                        </p>
                    </div>

                    <div class="form-group">
                        <input type="hidden" asp-for="AantalMaaltijden" />
                        <input type="hidden" id="Layout" value="@{TempData["Layout"] = Layout;}" />
                    </div>
            </div>

                 
            <div class="card-footer bg-warning">
                    <input type="submit" value="Save" class="btn btn-primary" />             
            </div>

        </form> 
        <!--hide/unhide form B message-->
        <div id ="card-body-msg1" class="card-body">
            <h5 class="card-title"><span class="text-danger">Bestelling in verwerking!!</span></h5>
            <p class="card-text">Je krijgt deze informatie boodschap te zien als de afhaaltijd minder dan één uur is. Deze bestelling kan niet meer gewijzigt of geannuleerd worden.</p>
        </div>
        

        <!--hide/unhide form C message-->
         <div id ="card-body-msg2" class="card-body">
            <h5 class="card-title"><span class="text-success">Bestelling Afgehandeld!!</span></h5>
            <p class="card-text">Je krijgt deze informatie boodschap te zien omdat deze bestelling afgeleverd is.</p>
        </div>

        <div id ="btnLijst" class="card-footer bg-warning">
             <a  class="btn btn-warning border-dark rounded-pill shadow border-4 mr-3" asp-area="" asp-controller="Bestellingen" asp-action="index">Overzicht bestellingen</a>
        </div>
    </div>



    <!--bestelbon overzicht-->
    <div id = "PrintSection" class="card text-center" width="25rem">
        <div class="card-header bg-info"><h5>BestelBon:</h5>  </div>
        <div class="card-body">
            <table class="table table-sm table-borderless" width="100%">
                    <tr>
                        <th col-span="2" class="text-center"><img class="mx-auto" src="/img/logo.png"  width="200" alt="Logo"> </th>
                        
                    </tr>
                    <tr>
                        <th> Klant:</th>
                        <th> Tijdslot:</th>
                    </tr>
                    <tr>
                        <td>
                            <p class="card-text text-left small">
                                @Model.KlantNaam <br />
                                @Model.Straat  @Model.HuisNr <br />
                                @Model.Postcode  @Model.Stad <br />
                                @Model.Email <br />
                                @Model.Telefoon <br />
                                @Model.Email <br />
                            </p>
                        </td>
                        <td>
                            <p class="card-text">
                                <h5><span id="tijdSlot" class="text-success">@Model.AfhaalTijdstip.ToShortDateString()</span></h5>
                                <h5><span id="tijdSlot" class="text-success">@Model.AfhaalTijdstip.ToShortTimeString()</span></h5>
                            </p>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <h5 class="card-title">Gerechten en opties:</h5>
                            <p>Aantal maaltijden in bestelling : @Model.AantalMaaltijden </p>
                            <table class="table table-striped border-secondary">
                                <thead class="thead-light">
                                    <tr>
                                        <th class="small font-weight-bold">Gerechtnaam</th>
                                        <th class="small font-weight-bold">Speciale Optie</th>
                                        <th class="small font-weight-bold">Prijs Gerecht</th>
                                        <th class="small font-weight-bold">Prijs Optie</th>
                                    </tr>
                                </thead>
                                <tr></tr>@*alternate the stripes color*@
                                @foreach (var item in Model.GerechtenLijst)
                                {             
                                    <tr>
                                        <td class="small">
                                            @item.GerechtNaam
                                        </td>
                                        <td class="small"> 
                                            @item.Optie
                                        </td>
                                        <td class="small">
                                            @item.GerechtPrijs €
                                        </td>
                                        <td class="small">
                                            @item.OptiePrijs €
                                        </td>
                                    </tr>
                                }
                            </table><br />
                             <h5 class="card-title">Totaal: <span class="text-danger">@ViewBag.TotaalPrijs €</span> </h5>
                             

                        </td>
                    </tr>
                </table>
        </div>
        <div class="card-footer bg-info ">
            <a class="btn btn-warning"  onclick="printDiv()">Print </a>
        </div>
    </div>
    </div>
 </div>
 


@section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

@*https://www.geeksforgeeks.org/print-the-contents-of-a-div-element-using-javascript/#:~:text=To%20print%20the%20content%20of,div%20element%20to%20be%20extracted.*@

 @*scripts om tijdslot te checken < uur*@

                @{double  dateTimeToMilliSeconds(DateTime d)
                    {
                        DateTime epoch = DateTime.UnixEpoch;
                        DateTime now = d;
 
                        TimeSpan ts = now.Subtract(epoch);
                        double unixTimeMilliseconds = ts.TotalMilliseconds;
 
                        return(unixTimeMilliseconds);
                    }

                 }


                <script>
                    tijdslotCheck('@Html.Raw(dateTimeToMilliSeconds(Model.AfhaalTijdstip))'); //execute the function   
                    
                    function tijdslotCheck(d)
                    {
                        let nu = Date.now(); //nu in millisec
  
                        console.log("nu " + nu);
                        console.log("d " + d);                      

                        const uur = 1000 * 60 * 60; // bereken hoeveel & uur is in milliseconds
                        console.log("uur " + uur);
                        

                       if(d < nu && d > nu - uur  ) //check 1 uur voor nu
                        { 
                            console.log("if1: "+ d +"<"+ nu +"&&"+ d +">"+ nu + "-" + uur);
                            document.getElementById("card-body-form").style.display = "none"; 
                            document.getElementById("card-body-msg2").style.display = "none"; 
                            document.getElementById("card-body-msg1").style.display = "block"; 
                       
                        } 

                        if(nu > d) // check if tijdslot voorbij is
                        { 
                            console.log("if2: "+ nu +">"+ d );
                            document.getElementById("card-body-form").style.display = "none"; 
                            document.getElementById("card-body-msg1").style.display = "none"; 
                            document.getElementById("card-body-msg2").style.display = "block";
                        } 
                        else
                        {
                            document.getElementById("card-body-msg1").style.display = "none"; 
                            document.getElementById("card-body-msg2").style.display = "none"; 
                            document.getElementById("btnLijst").style.display = "none"; 
                        }
                    }


                    
                </script>
               @* -----------------*@

Lekkerbek.web/Views/Bestellingen/EmailConfirmMsg.cshtml
@{
     ViewData["Title"] = "GeenKoksMsg";
     Layout=ViewBag.Layout;

}


<div class="card-deck">

    <div class="card text-center" style="max-width:25rem;">
        <div class="card-header bg-warning"><h5>Alert!!</h5>  </div>
        <img src="/img/ordering.png" class="card-img-top">
        <div class="card-body">
            <h3>Mail is verstuurd</h3><br />
            
        </div>
        <div class="card-footer bg-warning">    
            <a  asp-controller="Bestellingen" asp-action="Index" >Back to Homepage</a>
        </div>
    </div>
</div>

Lekkerbek.web/Views/Bestellingen/Factuur.cshtml
@model Lekkerbek.web.Models.FactuurModel

@{
	ViewData["Title"] = "Factuur";
	Layout = "~/Views/Shared/_LayoutFactuur.cshtml";
	string rol = ViewBag.Rol;
	bool korting = ViewBag.Korting;
}

<div class="container bg-light">
<div class="row">
    				<!-- BEGIN INVOICE -->
					<div id = "PrintSection">
					<div class="col-xs-12">
						<div class="grid invoice">
							<div class="grid-body">
								<div class="invoice-title">
									<div class="row">
										<div class="col-xs-12">
											<img src="/img/logo.png"  alt="Logo"  height="35">
										</div>
									</div>
									<br>
									<div class="row">
										<div class="col-xs-12">
											<h2>Factuur</h2><br>
											<span class="small">@Model.Id</span>
										</div>
									</div>
								</div>
								<hr>
								<div class="row">
									<div class="col-6">
										<address>
											<strong>Facturatie Adres:</strong><br>
											@Model.KlantNaam<br>
											@Model.Straat @Model.HuisNr<br>
											@Model.Postcode @Model.Stad<br>
											<abbr title="Telefoon">T:</abbr> @Model.Telefoon
										</address>
									</div>
									<div class="col-6 text-right">
										<address>
											<strong>BedrijfsAdres:</strong><br>
											@Model.BedrijfNaam<br>
											@Model.BedrijfStraat @Model.BedrijfHuisNr<br>
											@Model.BedrijfPostcode @Model.BedrijfStad<br>
											<abbr title="Telefoon">T:</abbr> @Model.BedrijfTelefoon<br>
											<abbr title="Email">E:</abbr> @Model.BedrijfEmail<br>
										</address>
									</div>
								</div>
								<div class="row">
									<div class="col-6">
										<address>
											<strong>Betaalwijze: </strong><br>
											@Model.Betaalwijze<br>
											@Model.Email<br>
										</address>
									</div>
									<div class="col-6 text-right">
										<address>
											<strong>Afhaaltijdstip:</strong><br>
											@Model.AfhaalTijdstip.ToShortDateString()
											@Model.AfhaalTijdstip.ToShortTimeString()
										</address>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<h3>BESTELLINGSOVERZICHT</h3>
										<table class="table table-striped">
											<thead>
												<tr class="line">
													<td><strong>#</strong></td>
													<td class="text-center"><strong>GERECHT</strong></td>
													<td class="text-center"><strong>OPTIE</strong></td>
													@*<td class="text-right"><strong>AANTAL</strong></td>*@
													<td class="text-right"><strong>PRIJS GERECHT</strong></td>
													<td class="text-right"><strong>PRIJS OPTIE</strong></td>
												</tr>
											</thead>
											<tbody>
											@{int count = 0;}
									@foreach (var item in Model.GerechtenLijst)
									{
										<tr>
											<td>@count</td>
											<td>@item.GerechtNaam</td>
											<td>@item.Optie</td>
											@*<td class="text-center">@item.Aantal</td>*@
											<td class="text-right">@item.GerechtPrijs €</td>
											<td class="text-right">@item.OptiePrijs</td>
										</tr>

										
											count++;
										
									}

												<tr>
													<td colspan="3"></td>
													<td class="text-right"><strong>Totaal Exclusief 21% BTW</strong></td>
													<td class="text-right"><strong>@ViewBag.TotaalPrijsZonderBtw €</strong></td>
												</tr>
												@if(korting == true)
												{
													<tr>
														<td colspan="3"></td>
															<td class="text-right"><strong>Klant Korting</strong></td>
															<td class="text-right"><strong>@ViewBag.KortingBedrag €</strong></td>
														</tr>
												}
									
												<tr>
													<td colspan="3"></td>
													<td class="text-right"><strong> 21% BTW</strong></td>
													<td class="text-right"><strong>@ViewBag.BtwBedrag €</strong></td>
												</tr>
												<tr>
													<td colspan="3">
													</td><td class="text-right"><strong>Totaal inclusief BTW</strong></td>
													<td class="text-right"><strong>@ViewBag.TotaalPrijsMetBtw</strong></td>
												</tr>
											</tbody>
										</table>
									</div>									
								</div>
								<div class="row">
									<div class="col-md-12 text-right identity">
										<p><strong>De lekkerbek dankt je voor het vertrouwen</strong></p>
									</div>
								</div>
							</div>
						</div>
					</div>
					</div>
					<!-- END INVOICE -->
				</div>
</div>    
    
<div>
   @if(rol =="Kassa")
            {
                <a class="btn border-warning btn-secondary"  onclick="printDiv()">Print Factuur </a>
               @* <a class="btn border-success btn-secondary"  asp-controller="Facturaties" asp-action="create"  asp-route-id="@Model.Id" >Afrekenen </a>*@
                <a class="btn border-primary btn-secondary"  asp-controller="Bestellingen"  asp-action="EmailFactuur" asp-route-id="@Model.Id" >Mail Factuur </a>
            }
    <a asp-action="Index">Back to List</a>
</div>

Lekkerbek.web/Views/Bestellingen/GeenKoksMsg.cshtml
@{
     ViewData["Title"] = "GeenKoksMsg";
     Layout=ViewBag.Layout;

}


<div class="card-deck">

    <div class="card text-center" style="max-width:25rem;">
        <div class="card-header bg-warning"><h5>Alert!!</h5>  </div>
        <img src="/img/ordering.png" class="card-img-top">
        <div class="card-body">
            <h3>Er zijn geen koks meer geprogrammeerd... </h3><br />
            (Of er kan geen tijdslot meer <br />
            geprogrammeerd worden 2 uur verder!)<br /><br />
            <i>Plan koks in om deze fout boodschap <br />
                te doen verdwijnen</i><br/>
        </div>
        <div class="card-footer bg-warning">    
            <a  asp-controller="Home" asp-action="home" asp-route-id ="1">Back to Homepage</a>
        </div>
    </div>
</div>

Lekkerbek.web/Views/Bestellingen/OldCreate.cshtml
@model Lekkerbek.web.Entities.TblBestelling

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TblBestelling</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KlantId" class="control-label"></label>
                <select asp-for="KlantId" class ="form-control" asp-items="ViewBag.KlantId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AfhaalTijdstip" class="control-label"></label>
                <input asp-for="AfhaalTijdstip" class="form-control" />
                <span asp-validation-for="AfhaalTijdstip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AantalMaaltijden" class="control-label"></label>
                <input asp-for="AantalMaaltijden" class="form-control" />
                <span asp-validation-for="AantalMaaltijden" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-area="" asp-controller="Bestellingen" asp-action="BesteldGerecht">Voeg gerecht toe</a><br />
               

               
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}